apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzVrY25WelkyaGxibU52T21kb2NGOVZORFV3Y1VkcVNrbEVZM1pLU0ROWVoycERUbVV5VnpOa2JVVjJaRXd6Y0Vsa1MxUT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
