apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
#  .dockerconfigjson: YW5kcnVzY2hlbmNvOmdocF9Mb3Jnak5aVW1XQXlveU93UDlRSThiY1VlcGtYc2MxWXptWHk=
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzVrY25WelkyaGxibU52T21kb2NGOU1iM0puYWs1YVZXMVhRWGx2ZVU5M1VEbFJTVGhpWTFWbGNHdFljMk14V1hwdFdIaz0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
