apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: cinemaabyss
  labels:
    app: proxy-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
        - name: proxy-service
#          image: ghcr.io/your-org/your-repo/proxy-service:latest
          image: ghcr.io/andruschenco/architecture-pro-cinemaabyss/proxy-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: MONOLITH_URL
              value: "http://monolith:8888"   # согласно TODO в коде
            - name: MOVIES_SERVICE_URL
              value: "http://movies-service:8081"
            - name: EVENTS_SERVICE_URL
              value: "http://events-service:80"   # через сервис events-service
            - name: GRADUAL_MIGRATION
              value: "true"
            - name: MOVIES_MIGRATION_PERCENT
              valueFrom:
                configMapKeyRef:
                  name: cinema-config
                  key: movies_migration_percent
          readinessProbe:
            httpGet:
              path: /health   # добавьте этот эндпоинт в прокси, если его нет
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: cinemaabyss
spec:
  selector:
    app: proxy-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP